package com.box.plantintest.presentation.common.designsystem.tokens

import androidx.compose.runtime.Immutable
import androidx.compose.ui.graphics.Color

@Immutable
data class PlantinColors(
    val primary: Color,
    val onPrimary: Color,
    val primaryContainer: Color,
    val onPrimaryContainer: Color,
    val secondary: Color,
    val onSecondary: Color,
    val secondaryContainer: Color,
    val onSecondaryContainer: Color,
    val background: Color,
    val onBackground: Color,
    val surface: Color,
    val onSurface: Color,
    val surfaceVariant: Color,
    val onSurfaceVariant: Color,
    val error: Color,
    val onError: Color,
    val errorContainer: Color,
    val onErrorContainer: Color,
    val success: Color,
    val onSuccess: Color,
    val successContainer: Color,
    val onSuccessContainer: Color,
    val warning: Color,
    val onWarning: Color,
    val warningContainer: Color,
    val onWarningContainer: Color,
    val outline: Color,
    val outlineVariant: Color,
    val scrim: Color,
    val inverseSurface: Color,
    val inverseOnSurface: Color,
    val inversePrimary: Color,
)

// Status-specific colors for character chips
@Immutable
data class PlantinStatusColors(
    val alive: Color,
    val onAlive: Color,
    val dead: Color,
    val onDead: Color,
    val unknown: Color,
    val onUnknown: Color,
)

val LightPlantinColors = PlantinColors(
    primary = Color(0xFF5C6BC0),
    onPrimary = Color.White,
    primaryContainer = Color(0xFFE8EAF6),
    onPrimaryContainer = Color(0xFF1A237E),
    secondary = Color(0xFF26A69A),
    onSecondary = Color.White,
    secondaryContainer = Color(0xFFE0F2F1),
    onSecondaryContainer = Color(0xFF00695C),
    background = Color(0xFFFCFCFF),
    onBackground = Color(0xFF1A1C1E),
    surface = Color.White,
    onSurface = Color(0xFF1A1C1E),
    surfaceVariant = Color(0xFFE2E2E9),
    onSurfaceVariant = Color(0xFF45464F),
    error = Color(0xFFB3261E),
    onError = Color.White,
    errorContainer = Color(0xFFF9DEDC),
    onErrorContainer = Color(0xFF410E0B),
    success = Color(0xFF2E7D32),
    onSuccess = Color.White,
    successContainer = Color(0xFFE8F5E8),
    onSuccessContainer = Color(0xFF1B5E20),
    warning = Color(0xFFF9A825),
    onWarning = Color.Black,
    warningContainer = Color(0xFFFFF8E1),
    onWarningContainer = Color(0xFF895A00),
    outline = Color(0xFF777680),
    outlineVariant = Color(0xFFC6C5D0),
    scrim = Color.Black,
    inverseSurface = Color(0xFF313033),
    inverseOnSurface = Color(0xFFF2F0F4),
    inversePrimary = Color(0xFFBDC2FF),
)

val DarkPlantinColors = PlantinColors(
    primary = Color(0xFFBDC2FF),
    onPrimary = Color(0xFF2C2F69),
    primaryContainer = Color(0xFF434682),
    onPrimaryContainer = Color(0xFFE0E0FF),
    secondary = Color(0xFF80CBC4),
    onSecondary = Color(0xFF003833),
    secondaryContainer = Color(0xFF00504A),
    onSecondaryContainer = Color(0xFF9EEAE0),
    background = Color(0xFF111318),
    onBackground = Color(0xFFE3E2E6),
    surface = Color(0xFF111318),
    onSurface = Color(0xFFE3E2E6),
    surfaceVariant = Color(0xFF45464F),
    onSurfaceVariant = Color(0xFFC6C5D0),
    error = Color(0xFFF2B8B5),
    onError = Color(0xFF601410),
    errorContainer = Color(0xFF8C1D18),
    onErrorContainer = Color(0xFFF9DEDC),
    success = Color(0xFF66BB6A),
    onSuccess = Color.Black,
    successContainer = Color(0xFF1B4E20),
    onSuccessContainer = Color(0xFFC8E6C9),
    warning = Color(0xFFFFD54F),
    onWarning = Color.Black,
    warningContainer = Color(0xFF6B4A00),
    onWarningContainer = Color(0xFFFFF0C4),
    outline = Color(0xFF8F9099),
    outlineVariant = Color(0xFF45464F),
    scrim = Color.Black,
    inverseSurface = Color(0xFFE3E2E6),
    inverseOnSurface = Color(0xFF313033),
    inversePrimary = Color(0xFF5C6BC0),
)

val LightStatusColors = PlantinStatusColors(
    alive = Color(0xFF2E7D32),
    onAlive = Color.White,
    dead = Color(0xFFC62828),
    onDead = Color.White,
    unknown = Color(0xFF757575),
    onUnknown = Color.White,
)

val DarkStatusColors = PlantinStatusColors(
    alive = Color(0xFF81C784),
    onAlive = Color.Black,
    dead = Color(0xFFE57373),
    onDead = Color.Black,
    unknown = Color(0xFFBDBDBD),
    onUnknown = Color.Black,
)
